### PR TITLE
Added Gutenberg support

### PR DESCRIPTION
**Pull request by bahiirwa**
Warning Breaking Changes for new version. 

It is imperative to have two new attribute fields `pretext` and `posttext`. If the language is easier, `before` and `after`. Traditionally, WP has been using `content`

No JS was harmed or used in the implementation of this PR.

Screenshots for process

In the classic Editor
screen shot 2019-01-10 at 11 09 26

In Block Editor
screen shot 2019-01-10 at 11 08 50

Both instances returned this
screen shot 2019-01-10 at 11 08 44

### CODE REVIEW

**Comment by johnalarcon** [comment]
Nice job, @bahiirwa.

Sorry if I wasn't clear on [Twitter](https://twitter.com/CodePotent/status/1082760357964177410). The plugin meets the need for which it was built, so there's no plans to update it. I thought you just wanted to add Gutenberg support for a personal project...didn't realize you were submitting a PR. :) Also, note that adding text directly to a shortcode in this way will cause it to be missed in translations.

**Comment by bahiirwa** [comment]
I did a small hack. It is ok if submit another plugin to the repo for the people who have been using your plugin but have since moved with GB? This is the change made to code.

4a190f7

**Comment by bahiirwa** [comment]
A PR is fine too. 💯

**Comment by johnalarcon** [comment]
I would recommend making your version backward compatible with the previous shortcodes since there's already a number of people using it and just taking over the code at the WP repo.

**Pull request closed without merging**
